### ISSUE TITLE
Broken in Node 10

### ISSUE THREAD

**Issue by pimterry** [natevw/struct-fu#18]
This is the cause of https://github.com/natevw/fatfs/issues/27

The problem is that `noAssert` has now been deprecated in node: https://github.com/nodejs/node/blob/2f12c959547e0118543ddd354e32a35795acb41d/doc/api/deprecations.md#dep0102-using-noassert-in-bufferreadwrite-operations

**Comment by natevw** [comment]
Thanks for tracking this down and the thorough pull request! Published as `struct-fu@1.2.1`.
