### ISSUE TITLE
Bit field endianness doesn't match C structs

### ISSUE THREAD

**Issue by andyfinity** [natevw/struct-fu#5]
I would like to read some binary written by a C struct that looks like:

    typedef struct {
        unsigned short id:14;
        unsigned char type:2;
        unsigned long size;
    } HEADER;
    
This particular struct turns

    HEADER h;
    h.id = 1;
    h.type = 2;
    h.size = 3;

into `0x014003000000` on x86 machines. Somewhat unfortunately, the result is in little-endian format. From what I can tell, I just need to use the following code to decode it:

    var _ = require('struct-fu'),
        sHeader = _.struct([
            _.ubitLE('id', 14),
            _.ubitLE('type', 2),
            _.uint32le('size')
        ]),
        header = sHeader.unpack(new Buffer('014003000000', 'hex'));

The result looks like:

    header = {
        id: 640,
        type: 0,
        size: 3
    }

Well, `size` is correct. But those bit field things look pretty wrong. It seems to interpret the hex input `0140` as binary `00000001 01000000` and dutifully begin parsing from left to right, least to most significant. I think little-endian hex `0140` should be interpreted as binary `10000000 00000010`, least to most significant.

This could be a PEBKAC error, me just not completely understanding how endianness works.

**Comment by natevw** [comment]
I don't think the C standards enforce any particular memory layout for bitfields. So it's not even so much of an endianness thing *per se* but rather that the compiler can layout the bitfields however it wants.

* http://stackoverflow.com/questions/1490092/c-c-force-bit-field-order-and-alignment
* http://stackoverflow.com/questions/15136426/memory-layout-of-struct-having-bitfields

As you've noticed struct-fu *does* guarantee a bitfield order parsing what we'd call "left to right" through the buffer. So if you convert your C logic to manually pack the bitfields (as you'll find recommended in the threads linked above) then struct-fu should be able to handle them as you'd expect.

In practice, compiler bitfield packing may be a bit more predictable [no pun intended?]:

* http://mjfrazer.org/mjfrazer/bitfields/

But yeah, I'm a little confused by how it's ending up with `0140` as the first two bytes. What compiler is this by the way?

What does the result from the C side look like if you convert this:

```
HEADER h;
h.id = 0x3FFF;
h.type = 0;
h.size = 0xFFFFFFFF;
```

**Comment by andyfinity** [comment]
Ah, I see what you mean about the lack of bitfield standards. The C side of things is being developed on a PIC24 chip using a GCC-based compiler, but the communication protocol is still open to development. At this point it sounds like our best bet is to avoid bitfields altogether since we can't guarantee we'll always use GCC.

But still, I made some [working demo C code](http://ideone.com/prgnMB)! Feel free to fork it and mess with variables and structures. I used it to generate some test cases for a related program. From what I can tell, they're running gcc-4.3.4 on some sort of Linux on x86.

Thanks for the input. I have definitely learned something today (on a weekend?! Heresy!).

**Comment by natevw** [comment]
Glad to hear! I'm going to close this, then, since I don't think there's much more I can do to follow up here in the library itself.

While it'd be nice to have (maybe as a wrapper library), I've never intended to support compiler-specific things like packing/padding or now this bitfield ordering stuff, in order to keep struct-fu itself simple. The idea is to make serialization "as easy as" C structs, but avoid the in-memory specifics [or rather, non-specified-ifics…] of those.
